{{- if .Values.logshipping.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: greenhouse-opensearch
  namespace: {{ .Chart.Name }}
data:
  username: {{ required ".Values.logshipping.opensearch.username missing" .Values.logshipping.opensearch.username | b64enc }}
  password: {{ required ".Values.logshipping.opensearch.password missing" .Values.logshipping.opensearch.password | b64enc }}
{{- end -}}
