apiVersion: greenhouse.sap/v1alpha1
kind: Organization
metadata:
  name: {{ .Chart.Name }}
spec:
  description: Greenhouse organization
  mappedOrgAdminIdPGroup: {{ required ".Values.teams.admin.mappedIdPGroup missing" .Values.teams.admin.mappedIdPGroup }}
{{- if.Values.oidc.enabled }}
  authentication:
    oidc:
      issuer: {{ required ".Values.oidc.issuer missing" .Values.oidc.issuer }}
      redirectURL: {{ required ".Values.oidc.redirectURL missing" .Values.oidc.redirectURL }}
      clientIDReference:
        name: {{ .Chart.Name }}-oidc
        key: clientID
      clientSecretReference:
        name: {{ .Chart.Name }}-oidc
        key: clientSecret
{{ end }}
