{{/* 
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}
{{ if .Values.organization.enabled }}
apiVersion: greenhouse.sap/v1alpha1
kind: Organization
metadata:
  name: {{ .Chart.Name }}
spec:
  description: Greenhouse organization
  mappedOrgAdminIdPGroup: {{ required ".Values.teams.admin.mappedIdPGroup missing" .Values.teams.admin.mappedIdPGroup }}
{{- if or .Values.global.oidc.enabled .Values.scim.enabled }}
  authentication:
{{- if.Values.global.oidc.enabled }}
    oidc:
      issuer: {{ required ".Values.global.oidc.issuer missing" .Values.global.oidc.issuer }}
      redirectURI: {{ default (printf "https://%s" ( include "idproxy.auth.hostname" .)) .Values.global.oidc.redirectURL }}
      clientIDReference:
        name: {{ .Chart.Name }}-auth
        key: oidcClientID
      clientSecretReference:
        name: {{ .Chart.Name }}-auth
        key: oidcClientSecret
    {{- if .Values.organization.oauth2ClientRedirectURIs }}
      oauth2ClientRedirectURIs:
        {{- .Values.organization.oauth2ClientRedirectURIs | toYaml | nindent 10 }}
    {{- end -}}
{{- end }}
{{- if .Values.scim.enabled }}
    scim:
      baseURL: {{ required ".Values.scim.baseURL" .Values.scim.baseURL }}
      basicAuthUser:
        secret:
          name: {{ .Chart.Name }}-auth
          key: scimBasicAuthUser
      basicAuthPw:
        secret:
          name: {{ .Chart.Name }}-auth
          key: scimBasicAuthPassword
{{ end }}
{{ end }}
{{ end }}
