{{- if or .Values.global.oidc.enabled .Values.scim.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-auth
  namespace: {{ .Chart.Name }}
  {{- $org := lookup "greenhouse.sap/v1alpha1" "Organization" .Chart.Name }}
  {{- if $org }}
  ownerReferences:
    - apiVersion: greenhouse.sap/v1alpha1
      kind: Organization
      name: {{ .Chart.Name }}
      uid: {{ $org.metadata.uid }}
  {{- end }}
type: greenhouse.sap/orgsecret
data:
{{- if .Values.global.oidc.enabled }}
  oidcClientID: {{ required ".Values.global.oidc.clientID missing" .Values.global.oidc.clientID | b64enc }}
  oidcClientSecret: {{ required ".Values.global.oidc.clientSecret missing" .Values.global.oidc.clientSecret | b64enc }}
{{ end }}
{{- if .Values.scim.enabled }}
{{- if .Values.scim.username }}
  scimBasicAuthUser: {{ .Values.scim.username | b64enc }}
{{ end }}
{{- if .Values.scim.username }}
  scimBasicAuthPassword: {{ .Values.scim.password | b64enc }}
{{ end }}
{{- if .Values.scim.bearerToken }}
  scimBearerToken: {{ .Values.scim.bearerToken | b64enc }}
{{ end }}
{{ end }}
{{ end }}
