{{/* 
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: greenhouse.sap/v1alpha1
kind: Organization
metadata:
  name: {{ .Chart.Name }}
spec:
  description: Greenhouse organization
  mappedOrgAdminIdPGroup: {{ required ".Values.teams.admin.mappedIdPGroup missing" .Values.teams.admin.mappedIdPGroup }}
{{- if or .Values.oidc.enabled .Values.scim.enabled }}
  authentication:
{{- if.Values.oidc.enabled }}
    oidc:
      issuer: {{ required ".Values.oidc.issuer missing" .Values.oidc.issuer }}
      redirectURL: {{ required ".Values.oidc.redirectURL missing" .Values.oidc.redirectURL }}
      clientIDReference:
        name: {{ .Chart.Name }}-oidc
        key: clientID
      clientSecretReference:
        name: {{ .Chart.Name }}-oidc
        key: clientSecret
{{ end }}
{{ if .Values.scim.enabled }}
    scim:
      baseURL: {{ required ".Values.scim.baseURL" .Values.scim.baseURL }}
      basicAuthUser:
        secret:
          name: {{ .Chart.Name }}-scim
          key: username
      basicAuthPw:
        secret:
          name: {{ .Chart.Name }}-scim
          key: password
{{ end }}
{{ end }}
