{{/* 
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if or .Values.global.oidc.enabled .Values.scim.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-auth
  namespace: {{ .Chart.Name }}
type: greenhouse.sap/orgsecret
data:
{{- if .Values.global.oidc.enabled }}
  oidcClientID: {{ required ".Values.global.oidc.clientID missing" .Values.global.oidc.clientID | b64enc }}
  oidcClientSecret: {{ required ".Values.global.oidc.clientSecret missing" .Values.global.oidc.clientSecret | b64enc }}
{{ end }}
{{- if .Values.scim.enabled }}
{{- if .Values.scim.username }}
  scimBasicAuthUser: {{ .Values.scim.username | b64enc }}
{{ end }}
{{- if .Values.scim.username }}
  scimBasicAuthPassword: {{ .Values.scim.password | b64enc }}
{{ end }}
{{- if .Values.scim.bearerToken }}
  scimBearerToken: {{ .Values.scim.bearerToken | b64enc }}
{{ end }}
{{ end }}
{{ end }}
