apiVersion: greenhouse.sap/v1alpha1
kind: Plugin
metadata:
  name: thanos
  namespace: {{ .Chart.Name }}
spec:
  disabled: false
  optionValues:
    {{- if and .Values.global.quayIoMirror .Values.global.ghcrIoMirror .Values.global.dockerHubMirror }}
    - name: thanos.image.repository
      value: {{ printf "%s/thanos/thanos" .Values.global.quayIoMirror }}
    - name: thanos.initChownData.image.registry
      value: {{ .Values.global.dockerHubMirror }}
    - name: testFramework.image.registry
      value: {{ .Values.global.ghcrIoMirror }}
    {{- end }}
    - name: thanos.query.autoDownsampling
      value: true
    - name: thanos.query.standalone
      value: false
    - name: thanos.query.stores
      value: []
    - name: thanos.query.ingress
      value:
        enabled: true
        annotations:
          disco: "true"
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: {{ .Values.thanos.ingress.host }}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - {{ required ".Values.thanos.ingress.host missing" .Values.thanos.ingress.host }}
            secretName: tls-{{ .Values.thanos.ingress.host | replace "." "-" }}
    - name: thanos.ruler.enabled
      value: false
    - name: thanos.store.enabled
      value: true
    - name: thanos.compactor.enabled
      value: true
  pluginDefinition: thanos
