apiVersion: greenhouse.sap/v1alpha1
kind: Plugin
metadata:
  name: perses
spec:
  disabled: false
  displayName: perses
  optionValues:
    - name: perses.ingress.annotations
      value:
        disco: "true"
        kubernetes.io/tls-acme: "true"
    - name: perses.ingress.enabled
      value: true
    - name: perses.ingress.hosts
      value:
        - host: {{ index .Values.perses.ingress.hosts 0 "host" }}
          paths:
            - path: /
              pathType: Prefix
    - name: perses.ingress.ingressClassName
      value: nginx
    - name: perses.ingress.tls
      value:
        - hosts:
            - {{ index .Values.perses.ingress.tls.hosts 0 }}
          secretName: {{ printf "%s-%s" "tls" (first .Values.perses.ingress.hosts).host | replace "." "-" }}
    - name: perses.sidecar.enabled
      value: true
  pluginDefinition: perses
