apiVersion: greenhouse.sap/v1alpha1
kind: Plugin
metadata:
  name: thanos
  namespace: {{ .Chart.Name }}
spec:
  disabled: false
  optionValues:
    {{- if and .Values.global.quayIoMirror .Values.global.ghcrIoMirror .Values.global.dockerHubMirror }}
    - name: thanos.image.repository
      value: {{ printf "%s/thanos/thanos" .Values.global.quayIoMirror }}
    - name: thanos.initChownData.image.registry
      value: {{ .Values.global.dockerHubMirror }}
    - name: testFramework.image.registry
      value: {{ .Values.global.ghcrIoMirror }}
    {{- end }}
    - name: thanos.query.autoDownsampling
      value: true
    - name: thanos.query.standalone
      value: true
    - name: thanos.query.stores
      value: []
    - name: thanos.ruler.enabled
      value: false
    - name: thanos.store.enabled
      value: true
    - name: thanos.compactor.enabled
      value: true
    - name: thanos.query.ingress.grpc.annotations
      value:
        disco: "true"
        kubernetes.io/tls-acme: "true"
    - name: thanos.query.ingress.grpc.enabled
      value: true
    - name: thanos.query.ingress.grpc.hosts
      value:
        - host: "thanos.{{ .Values.global.dnsDomain }}"
          paths:
            - path: /
              pathType: Prefix
    - name: thanos.query.ingress.grpc.ingressClassName
      value: nginx
    - name: thanos.query.ingress.grpc.tls
      value:
        - hosts:
            - "thanos.{{ .Values.global.dnsDomain }}"
          secretName: {{ printf "tls-%s" (print "thanos." .Values.global.dnsDomain | replace "." "-") }}
  pluginDefinition: thanos
