{{/* 
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.logshipping.enabled }}
apiVersion: greenhouse.sap/v1alpha1
kind: Plugin
metadata:
  name: logshipper-greenhouse
  namespace: {{ .Release.Namespace }}
spec:
  pluginDefinition: logshipper
  disabled: false
  optionValues:
    - name: fluent-bit.parser
      value: "cri"
    - name: fluent-bit.backend.opensearch.enabled
      value: true
    - name: fluent-bit.backend.opensearch.host
      value: {{ required "opensearch host missing" .Values.logshipping.opensearch.host }}
    - name: fluent-bit.backend.opensearch.port
      value: {{ default "9200" .Values.logshipping.opensearch.port | quote }}
    - name: fluent-bit.backend.opensearch.http_user
      valueFrom:
        secret:
          name: greenhouse-opensearch
          key: username
    - name: fluent-bit.backend.opensearch.http_password
      valueFrom:
        secret:
          name: greenhouse-opensearch
          key: password
    - name: fluent-bit.backend.opensearch.logstash_prefix
      value: {{ index .Values "logshipping" "opensearch" "logstashPrefix" }}
    - name: prometheusName
      value: "kube-monitoring"
    - name: fluent-bit.image.repository
      value: {{ index .Values "logshipping" "fluent-bit" "image" "repository" }}
    - name: fluent-bit.hotReload.image.repository
      value: {{ index .Values "logshipping" "fluent-bit" "hotReload" "image" "repository" }}
    - name: fluent-bit.filter.additionalValues
      value:
        {{- index .Values "logshipping" "fluent-bit" "additionalValues" | toYaml | nindent 8 -}}
{{ if .Values.logshipping.octobus }}
    - name: fluent-bit.customConfig.inputs: |-
        [INPUT]
            Name             tail
            Path             /var/log/containers/greenhouse-controller-manager*.log
            Parser           cri
            Tag              audit.*
            Refresh_Interval 5
            Mem_Buf_Limit    50MB
            Skip_Long_Lines  Off
            Ignore_Older     1m
            DB               /var/log/fluent-bit-audit-tail.pos.db
    - name: fluent-bit.customConfig.filters: |-
        [FILTER]
            Name               grep
            Match              audit.*
            Regex              AdmissionRequest
        
        [FILTER]
            Name record_modifier
            Match *
            Record sap.cc.audit_source greenhouse
            Record sap.cc.cluster {{ index .Values "global" "cluster" }}
            Record sap.cc.region {{ index .Values "global" "region" }}
    - name: fluent-bit.customConfig.outputs: |-
        [OUTPUT]
            Name  http
            Match audit.*
            Host  {{ index .Values "fluent-bit" "backend" "octobus" "host"}}
            Port  443
            URI   {{ index .Values "fluent-bit" "backend" "octobus" "uri"}}
            Format json_lines
            tls true
            tls.verify true
            tls.ca_file /etc/ssl/certs/ca-certificates.crt
    - name: fluent-bit.backend.octobus.host
      value: {{ index .Values "logshipping" "octobus" "host" }}
    - name: fluent-bit.backend.octobus.uri
      value: {{ index .Values "logshipping" "octobus" "uri" }}
{{- end -}}
{{- end -}}
