{{ if and .Values.plugins.enabled .Values.plutono.enabled }}
apiVersion: greenhouse.sap/v1alpha1
kind: Plugin
metadata:
  name: plutono
spec:
  optionValues:
    - name: plutono.ingress.enabled
      value: true
    - name: plutono.ingress.annotations
      value:
        disco: "true"
        kubernetes.io/tls-acme: "true"
    - name: plutono.ingress.hosts
      value:
        - host: "plutono.{{ .Values.global.dnsDomain }}"
    - name: plutono.ingress.tls
      value:
        - hosts:
          - "plutono.{{ .Values.global.dnsDomain }}"
          secretName: {{ printf "tls-%s" (print "plutono." .Values.global.dnsDomain | replace "." "-") }}
  pluginDefinition: plutono
{{ end }}
