{{/* 
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}
{{ if .Values.plugins.enabled}}
apiVersion: greenhouse.sap/v1alpha1
kind: Plugin
metadata:
  name: cert-manager
  namespace: {{ .Chart.Name }}
spec:
  pluginDefinition: cert-manager
  disabled: false
{{ if .Values.digicertIssuer.enabled }}
  optionValues:
    - name: cert-manager.ingressShim.defaultIssuerName
      value: digicert-issuer
    - name: cert-manager.ingressShim.defaultIssuerKind
      value: DigicertIssuer
    - name: cert-manager.ingressShim.defaultIssuerGroup
      value: certmanager.cloud.sap
{{ end }}
{{ end }}
