{{/* 
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if.Values.scim.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-scim
  namespace: {{ .Chart.Name }}
data:
  username: {{ required ".Values.scim.username missing" .Values.scim.username | b64enc }}
  password: {{ required ".Values.scim.password missing" .Values.scim.username | b64enc }}
{{ end }}
