apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "manager.fullname" . }}-kube-webhook-certgen
  namespace: greenhouse
  labels:
  {{- include "manager.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "manager.fullname" . }}-kube-webhook-certgen
  labels:
  {{- include "manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "manager.fullname" . }}-kube-webhook-certgen
  labels:
  {{- include "manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "manager.fullname" . }}-kube-webhook-certgen
  labels:
  {{- include "manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "manager.fullname" . }}-kube-webhook-certgen'
subjects:
- kind: ServiceAccount
  name: '{{ include "manager.fullname" . }}-kube-webhook-certgen'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "manager.fullname" . }}-kube-webhook-certgen
  labels:
  {{- include "manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "manager.fullname" . }}-kube-webhook-certgen'
subjects:
- kind: ServiceAccount
  name: '{{ include "manager.fullname" . }}-kube-webhook-certgen'
  namespace: '{{ .Release.Namespace }}'