# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "manager.fullname" . }}-manager-config
  labels:
  {{- include "manager.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: |
    {{- .Files.Get "etc/controller_manager_config.yaml" | nindent 4 }}
