
{{- if .Values.alerts.enabled }}
{{- range $path, $bytes := .Files.Glob "alerts/*.alerts" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: operator
    role: alert-rules
    plugin: kube-monitoring
  name: {{ include "manager.fullname" $ }}-controller-manager-alerts
spec:
{{ printf "%s" $bytes | indent 2 }}
{{- end }}
{{- end }}
