---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "manager.fullname" . }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  - secrets
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - dex.coreos.com
  resources:
  - connectors
  - oauth2clients
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greenhouse.sap
  resources:
  - cluster-kubeconfigs
  - teamroles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greenhouse.sap
  resources:
  - clusters
  - organizations
  - plugindefinitions
  - plugins
  - teammemberships
  - teamrolebindings
  - teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greenhouse.sap
  resources:
  - clusters/finalizers
  - organizations/finalizers
  - pluginpresets/finalizers
  - plugins/finalizers
  - teamrolebindings/finalizers
  - teams/finalizers
  verbs:
  - update
- apiGroups:
  - greenhouse.sap
  resources:
  - clusters/status
  - organizations/status
  - pluginpresets/status
  - plugins/status
  - teammemberships/status
  - teamrolebindings/status
  - teams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - greenhouse.sap
  resources:
  - pluginpresets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - rbac
  resources:
  - clusterrolebindings
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
