apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "manager.fullname" . }}-metrics-reader
  namespace: greenhouse
  labels:
  {{- include "manager.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get