apiVersion: v1
kind: Service
metadata:
  name: {{ include "manager.fullname" . }}-controller-manager-metrics-service
  namespace: greenhouse
  labels:
    app: greenhouse
    {{- include "manager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: greenhouse
    {{- include "manager.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
