# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "manager.fullname" . }}-plugin-viewer-role
  namespace: greenhouse
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: greenhouse
    app.kubernetes.io/part-of: greenhouse
    greenhouse.sap/aggregate-to-organization-cluster-resource-viewer: "true"
  {{- include "manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - greenhouse.sap
  resources:
  - plugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - greenhouse.sap
  resources:
  - plugins/status
  verbs:
  - get