apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "manager.fullname" . }}-controller-manager
  namespace: greenhouse
  labels:
  {{- include "manager.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
