# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: greenhouse-webhook-service
  namespace: greenhouse
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: greenhouse
    app.kubernetes.io/part-of: greenhouse
  {{- include "manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type | default "ClusterIP" }}
  selector:
    app: greenhouse
  {{- include "manager.selectorLabels" . | nindent 4 }}
  ports:
 {{- .Values.webhookService.ports | toYaml | nindent 2 -}}
