---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: greenhouse-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /mutate-greenhouse-sap-v1alpha1-cluster
    failurePolicy: Fail
    name: mcluster.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusters
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /mutate-greenhouse-sap-v1alpha1-organization
    failurePolicy: Fail
    name: morganization.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - organizations
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /mutate-greenhouse-sap-v1alpha1-plugin
    failurePolicy: Fail
    name: mplugin.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - plugins
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /mutate-greenhouse-sap-v1alpha1-plugindefinition
    failurePolicy: Fail
    name: mplugindefinition.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - plugindefinitions
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /mutate-greenhouse-sap-v1alpha1-pluginpreset
    failurePolicy: Fail
    name: mpluginpreset.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pluginpresets
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /mutate-greenhouse-sap-v1alpha1-teamrole
    failurePolicy: Fail
    name: mrole.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - teamroles
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /mutate-greenhouse-sap-v1alpha1-teamrolebinding
    failurePolicy: Fail
    name: mrolebinding-v1alpha1.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - teamrolebindings
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /mutate--v1-secret
    failurePolicy: Ignore
    matchPolicy: Exact
    name: msecret.kb.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - secrets
    sideEffects: None
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /mutate-greenhouse-sap-v1alpha1-team
    failurePolicy: Fail
    name: mteam.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - teams
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /mutate-greenhouse-sap-v1alpha2-teamrolebinding
    failurePolicy: Fail
    name: mrolebinding-v1alpha2.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - teamrolebindings
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: greenhouse-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /validate-greenhouse-sap-v1alpha1-cluster
    failurePolicy: Fail
    name: vcluster.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - clusters
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /validate-greenhouse-sap-v1alpha1-organization
    failurePolicy: Fail
    name: vorganization.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - organizations
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /validate-greenhouse-sap-v1alpha1-plugin
    failurePolicy: Fail
    name: vplugin.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - plugins
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /validate-greenhouse-sap-v1alpha1-plugindefinition
    failurePolicy: Fail
    name: vplugindefinition.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - plugindefinitions
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /validate-greenhouse-sap-v1alpha1-pluginpreset
    failurePolicy: Fail
    name: vpluginpreset.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - pluginpresets
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /validate-greenhouse-sap-v1alpha1-teamrole
    failurePolicy: Fail
    name: vrole.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - teamroles
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /validate-greenhouse-sap-v1alpha1-teamrolebinding
    failurePolicy: Fail
    name: vrolebinding-v1alpha1.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - teamrolebindings
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /validate--v1-secret
    failurePolicy: Ignore
    matchPolicy: Exact
    name: vsecret.kb.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - secrets
    sideEffects: None
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /validate-greenhouse-sap-v1alpha1-team
    failurePolicy: Fail
    name: vteam.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - teams
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: greenhouse-webhook-service
        namespace: greenhouse
        path: /validate-greenhouse-sap-v1alpha2-teamrolebinding
    failurePolicy: Fail
    name: vrolebinding-v1alpha2.kb.io
    rules:
      - apiGroups:
          - greenhouse.sap
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - teamrolebindings
    sideEffects: None
