# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

before:
  hooks:
    - go mod tidy

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GIT_BRANCH=$(shell git rev-parse --abbrev-ref HEAD)
  - GIT_COMMIT=$(shell git rev-parse --short HEAD)
  - GIT_STATE=$(shell if git diff --quiet; then echo clean; else echo dirty; fi)
  - BUILD_DATE=$(shell date -u +"%Y-%m-%dT%H:%M:%SZ")
  - LDFLAGS=-s -w -X github.com/cloudoperators/greenhouse/internal/version.GitBranch=$(GIT_BRANCH) -X github.com/cloudoperators/greenhouse/internal/version.GitCommit=$(GIT_COMMIT) -X github.com/cloudoperators/greenhouse/internal/version.GitState=$(GIT_STATE) -X github.com/cloudoperators/greenhouse/internal/version.BuildDate=$(BUILD_DATE)

git:
  tag_sort: -version:creatordate

builds:
  - id: linux-amd64
    binary: greenhousectl-linux-{{ .Arch }}
    main: ./cmd/greenhousectl/main.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    no_unique_dist_dir: true

  - id: darwin-amd64
    binary: greenhousectl-darwin-{{ .Arch }}
    main: ./cmd/greenhousectl/main.go
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    no_unique_dist_dir: true

checksum:
  name_template: "checksums.txt"

archives:
  - formats: [
      'tar.gz'
    ]
    name_template: >-
      {{ .ProjectName }}ctl_
      {{- .Version -}}_
      {{- .Os -}}-{{.Arch}}
    files:
      - README.md
