# REUSE-IgnoreStart
header:
  license:
    spdx-id: Apache-2.0
    content: |
      SPDX-FileCopyrightText: [year] SAP SE or an SAP affiliate company and Greenhouse contributors
      SPDX-License-Identifier: Apache-2.0
    pattern: |
      SPDX-FileCopyrightText: [0-9]+ SAP SE or an SAP affiliate company and Greenhouse contributors
      SPDX-License-Identifier: Apache-2\.0
# REUSE-IgnoreEnd

  paths: # `paths` are the path list that will be checked (and fixed) by license-eye, default is ['**'].
    - '**'

  paths-ignore:
    - '.github/**'
    - 'REUSE.toml'
    - 'LICENSES/*.txt'
    - 'website/scripts/**'
    - 'hack/**'
    - 'hack/openapi-generator/openapi-info.yaml'
    - 'hack/boilerplate.go.txt'
    - 'hack/typescript/metadata.yaml'
    - 'docs/**'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - 'PROJECT'
    - '**/*.gitignore'
    - '**/*.helmignore'
    - '**/*.tpl'
    - '**/*.alerts'
    - '**/go.mod'
    - '**/go.sum'
    - '**/*.lock'
    - '**/*.json'
    - '**/.gitkeep'
    - '**/*.txt'
    - '*Dockerfile*'
    - 'Makefile'
    - 'internal/dex/web/**'
    - '**/zz_generated.deepcopy.go' # Generated by Kubebuilder
    - 'charts/**/templates/**/*.yaml' # license headers on helm templates are causing issues
    - '.mockery.yaml'     # Mockery config file
    - 'internal/mocks/**'    # Mockery generated files
    - 'config/flux/**'  #Flux CD files
    - 'config/manifest/**'  #Flux CD files

  comment: on-failure
  
  # license-location-threshold specifies the index threshold where the license header can be located,
  # after all, a "header" cannot be TOO far from the file start.
  license-location-threshold: 80

  language:
    JSX: 
      extensions:
        - ".jsx"
      comment_style_id: SlashAsterisk
