header:
  license:
    spdx-id: Apache-2.0
    content: |
      SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
      SPDX-License-Identifier: Apache-2.0

  paths: # `paths` are the path list that will be checked (and fixed) by license-eye, default is ['**'].
    - '**'

  paths-ignore:
    - '.github/**'
    - '.reuse/dep5'
    - 'LICENSES/*.txt'
    - 'grafana/*.json'
    - 'website/scripts/**'
    - 'hack/**'
    - 'hack/openapi-generator/openapi-info.yaml'
    - 'hack/boilerplate.go.txt'
    - 'docs/**'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - 'PROJECT'
    - '**/*.gitignore'
    - '**/*.helmignore'
    - '**/*.tpl'
    - '**/go.mod'
    - '**/go.sum'
    - '**/*.lock'
    - '**/*.json'
    - '**/.gitkeep'
    - '**/*.txt'
    - '*Dockerfile*'
    - 'Makefile'
    - 'pkg/idproxy/web/**'
    - 'pkg/apis/scheme_builder.go' # Belongs to the Kubernetes authors
    - 'cmd/tcp-proxy/main.go' # MIT License
    - 'pkg/tcp-proxy/proxy/*.go' # MIT License
    - '**/zz_generated.deepcopy.go' # Generated by Kubebuilder
    - 'charts/**/templates/*.yaml' # license headers on helm templates are causing issues 
    

  comment: on-failure
  
  # license-location-threshold specifies the index threshold where the license header can be located,
  # after all, a "header" cannot be TOO far from the file start.
  license-location-threshold: 80

  language:
    JSX: 
      extensions:
        - ".jsx"
      comment_style_id: SlashAsterisk
