header:
  license:
    spdx-id: Apache-2.0
    content: |
      SPDX-FileCopyrightText: 2024-2026 SAP SE or an SAP affiliate company and Greenhouse contributors
      SPDX-License-Identifier: Apache-2.0

  paths: # `paths` are the path list that will be checked (and fixed) by license-eye, default is ['**'].
    - '**'

  paths-ignore:
    - '.github/**'
    - 'charts/**'
    - '.reuse /dep5'
    - 'LICENSES/*.txt'
    - 'grafana/*.json'
    - 'website/scripts/**'
    - 'hack/**'
    - 'docs/**'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - 'PROJECT'
    - '**/*.gitignore'
    - '**/go.mod'
    - '**/go.sum'
    - '**/*.yaml'
    - '**/*.lock'
    - '**/*.json'
    - '**/.gitkeep'
    - '**/*.jsx'
    - '**/*.txt'
    - '*Dockerfile*'
    - 'Makefile'
    - '**/*.svg'
    - 'pkg/apis/scheme_builder.go' # Belongs to the Kubernetes authors
    - 'cmd/tcp-proxy/main.go' # MIT License
    - 'pkg/tcp-proxy/proxy/*.go' # MIT License
    

  comment: on-failure
  
  # license-location-threshold specifies the index threshold where the license header can be located,
  # after all, a "header" cannot be TOO far from the file start.
  license-location-threshold: 80
