dir: pkg/mocks
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/cloudoperators/greenhouse/pkg/lifecycle:
    interfaces:
      Reconciler:
        config:
          filename: "mock_{{.InterfaceName}}.go"
  github.com/dexidp/dex/storage:
    interfaces:
      Storage:
        config:
          filename: "mock_{{.InterfaceName}}.go"
  sigs.k8s.io/controller-runtime/pkg/client:
    interfaces:
      Client:
        config:
          filename: "mock_{{.InterfaceName}}.go"
      SubResourceWriter:
        config:
          filename: "mock_{{.InterfaceName}}.go"
