# .mockery.yaml
with-expecter: false
filename: "mock_{{.InterfaceName}}.go"
outpkg: mocks
dir: internal/mocks
packages:
  github.com/cloudoperators/greenhouse/internal/lifecycle:
    interfaces:
      Reconciler:
  sigs.k8s.io/controller-runtime/pkg/client:
    interfaces:
      Client:
      SubResourceWriter:
  github.com/dexidp/dex/storage:
    interfaces:
      Storage:
