dir: internal/mocks
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/cloudoperators/greenhouse/internal/lifecycle:
    config:
      filename: "mock_{{.InterfaceName}}.go"
    interfaces:
      Reconciler: {}
  github.com/dexidp/dex/storage:
    config:
      filename: "mock_{{.InterfaceName}}.go"
    interfaces:
      Storage: {}
  sigs.k8s.io/controller-runtime/pkg/client:
    config:
      filename: "mock_{{.InterfaceName}}.go"
    interfaces:
      Client: {}
      SubResourceWriter: {}
