# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0


FROM node:20.18-alpine3.20
LABEL source_repository="https://github.com/cloudoperators/greenhouse"
WORKDIR /app
COPY ./ui/dashboard /app
COPY ./dev-env/build/greenhouse-ui/secretProps.json /app
COPY ./ui/helpers/appProps.js /helpers/appProps.js
RUN cd /app && npm add -D esbuild && npm install && npm run build

CMD [ "npm", "start"]

