FROM floryn90/hugo:0.125.2-ext-debian
LABEL source_repository="https://github.com/cloudoperators/greenhouse"

COPY docs /docs
COPY website /src

WORKDIR /src
RUN ["make", "content" ]
RUn ["rm", "-rf", "/docs" ]
RUN ["hugo", "mod", "clean"]
RUN ["hugo", "mod", "vendor"]
ENTRYPOINT ["hugo", "server"]
