# Build the manager binary
FROM --platform=${BUILDPLATFORM:-linux/amd64} golang:1.21 as builder

ARG TARGETOS
ARG TARGETARCH
ENV CGO_ENABLED=0
ENV ENVTEST_K8S_VERSION=1.29.3
WORKDIR /workspace

COPY . .

# Build dev-env and setup-envtest
RUN --mount=type=cache,target=/go/pkg/mod \
  --mount=type=cache,target=/root/.cache/go-build \
  make generate build-dev-env CGO_ENABLED=${CGO_ENABLED} GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
  && GOBIN=/workspace/bin go install sigs.k8s.io/controller-runtime/tools/setup-envtest@bf15e44028f908c790721fc8fe67c7bf2d06a611 \
  && cp $(/workspace/bin/setup-envtest use ${ENVTEST_K8S_VERSION} -p path)/* /usr/local/bin


# final image 
FROM --platform=${BUILDPLATFORM:-linux/amd64} alpine:3.20.0
LABEL source_repository="https://github.com/cloudoperators/greenhouse"
ENV KUBEBUILDER_ASSETS=/usr/local/bin
WORKDIR /
COPY --from=builder /workspace/bin/* .
COPY --from=builder /workspace/charts/manager/crds ./config/crd/bases
COPY --from=builder /workspace/charts/idproxy/crds ./charts/idproxy/crds
COPY --from=builder /workspace/charts/manager/templates/webhooks.yaml ./config/webhook/webhooks.yaml
COPY --from=builder /usr/local/bin ./usr/local/bin
RUN apk add --no-cache libc6-compat

CMD /dev-env && \
  echo "proxying ${DEV_ENV_CONTEXT:-cluster-admin}" && \
  kubectl proxy --kubeconfig=/envtest/internal.kubeconfig --context=${DEV_ENV_CONTEXT:-cluster-admin} --port=8090 --v=9 --address="0.0.0.0" --accept-hosts "^.*$"
