# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: flux-system
spec:
  selector:
    app: registry
  ports:
    - name: registry
      port: 5000
      targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: flux-system
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      enableServiceLinks: true
      containers:
        - name: registry
          image: "registry:3"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/cert.pem
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/key.pem
            - name: REGISTRY_LOG_LEVEL
              value: info
            - name: OTEL_TRACES_EXPORTER
              value: none
          volumeMounts:
            - mountPath: /certs
              name: local-registry-tls-certs
          readinessProbe:
            httpGet:
              path: /v2/
              port: 5000
              scheme: HTTPS
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 25
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /v2/
              port: 5000
              scheme: HTTPS
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 25
            failureThreshold: 3
          resources:
            limits:
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 512Mi
      volumes:
        - name: registry
          emptyDir: {}
        - name: local-registry-tls-certs
          secret:
            items:
              - key: tls.crt
                path: cert.pem
              - key: tls.key
                path: key.pem
              - key: ca.crt
                path: ca.pem
            secretName: local-registry-tls-certs