teams:
  demo:
    description: Team for demonstration purposes

# User for demonstration purposes to be assigned to every team.
demoUser:
  email: demo@example.com
  firstName: demo
  id: D000000
  lastName: greenhouse

# Plugins to be shown in the demo setup are configured below.
alerts:
  enabled: false
  # Supernova options.
  endpoint:

  slack:
    channel:
    webhookURL:

  ingress:
    host:

  filterLabels:
    - app
    - service
    - severity
  silenceExcludedLabels:
    - pod
    - pod_name
    - instance
  # Alertmanager options.
  alertmanager:
    # Whether to deploy the alertmanager.
    enabled: false

  # endpoint for the CronJob to send the dummy alerts to
  generator:
    endpoint: "alerts-alertmanager.demo.svc:9093"

doop:
  enabled: true
  displayName: Violations
