# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml
