apiVersion: v1
kind: Service
metadata:
  name: {{ include "manager.fullname" . }}-controller-manager-metrics-service
  namespace: greenhouse
  labels:
    app.kubernetes.io/created-by: {{ include "manager.fullname" . }}
    app.kubernetes.io/part-of: {{ include "manager.fullname" . }}
{{- include "webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
