# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

ingress:
  enabled: true
  host: headscale.example.com

grpc:
  insecure: true
  ingress:
    enabled: true
    host: headscale-grpc.example.com

postgres:
  password: topSecret!

oidc:
  enabled: true
  issuer: https://auth.greenhouse.com
  clientID: topSecret!
  clientSecret: topSecret!
  allowedGroups:
    - role:greenhouse:admin
