#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

# Wrapper for https://github.com/srfrnk/crd-api-doc-gen preserving the openapi.yaml.
# Call this using generate-openapi-spec-from-crds

set -o errexit
set -o nounset
set -o pipefail

# Check arguments.
if [[ $# -ne 3 ]]; then
    echo "usage: call this wrapper using generate-openapi-spec-from-crds" >&2
    exit 2
fi

cp "$3" /tmp/openapi-info.yaml
yq e --inplace '.api-info.version = env(VERSION)' /tmp/openapi-info.yaml

# Generate openapi spec and documentation.
/generate.sh $1 /tmp /tmp/openapi-info.yaml

# Cleanup.
rm -rf $2/.openapi-generator $2/.openapi-generator-ignore || true
# Only update openapi.yaml, we do not create index.html with this tool.
cp /tmp/data/api.yaml $2/openapi.yaml

