#!/usr/bin/env bash

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Wrapper for https://github.com/srfrnk/crd-api-doc-gen preserving the openapi.yaml.
# Call this using generate-openapi-spec-from-crds

set -o errexit
set -o nounset
set -o pipefail

# Check arguments.
if [[ $# -ne 3 ]]; then
    echo "usage: call this wrapper using generate-openapi-spec-from-crds" >&2
    exit 2
fi

cp "$3" /tmp/openapi-info.yaml
yq e --inplace '.api-info.version = env(VERSION)' /tmp/openapi-info.yaml

# Generate openapi spec and documentation.
/generate.sh $1 $2 /tmp/openapi-info.yaml

# Cleanup.
rm -rf $2/.openapi-generator $2/.openapi-generator-ignore || true
# Preserve openapi.yaml.
cp /tmp/data/api.yaml $2/openapi.yaml
