#!/usr/bin/env bash

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generates openapi documentation using https://github.com/srfrnk/crd-api-doc-gen

set -o errexit
set -o nounset
set -o pipefail

# Check arguments.
if [[ $# -ne 3 ]]; then
    echo "usage: generate-openapi-spec-from-crds <CRD manifest directory> <version> <output directory>" >&2
    exit 2
fi
MANIFESTS_DIR=$1
VERSION=$2
OUTPUT_DIR=$3

echo "generating openapi specification from manifests ${MANIFESTS_DIR} to ${OUTPUT_DIR}"
REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"
docker run --user 1001 --rm -v "${MANIFESTS_DIR}:/manifests" -v "${REPO_ROOT}":/src --entrypoint "/src/hack/openapi-generator/_generate-wrapper" --env VERSION="${VERSION}" ghcr.io/srfrnk/crd-api-doc-gen:latest "/manifests" "/src/${OUTPUT_DIR}" "/src/hack/openapi-generator/openapi-info.yaml"
