#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

# Generates openapi documentation using https://github.com/srfrnk/crd-api-doc-gen

set -o errexit
set -o nounset
set -o pipefail

# Check arguments.
if [[ $# -ne 3 ]]; then
    echo "usage: generate-openapi-spec-from-crds <CRD manifest directory> <version> <output directory>" >&2
    exit 2
fi
MANIFESTS_DIR=$1
VERSION=$2
OUTPUT_DIR=$3

echo "generating openapi specification from manifests ${MANIFESTS_DIR} to ${OUTPUT_DIR}"
REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"
docker run --platform linux/amd64 --user 1001 --rm -v "${MANIFESTS_DIR}:/manifests" -v "${REPO_ROOT}":/src --entrypoint "/src/hack/openapi-generator/_generate-wrapper" --env VERSION="${VERSION}" ghcr.io/srfrnk/crd-api-doc-gen:latest "/manifests" "/src/${OUTPUT_DIR}" "/src/hack/openapi-generator/openapi-info.yaml"
