---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "manager.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "manager.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "manager.fullname" . }}-controller-manager
  namespace: greenhouse 
