apiVersion: v1
kind: Service
metadata:
  name: {{ include "manager.fullname" . }}-webhook-service
  namespace: greenhouse
  labels:
    app.kubernetes.io/created-by: {{ include "manager.fullname" . }}
    app.kubernetes.io/part-of: {{ include "manager.fullname" . }}
{{- include "webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type | default "ClusterIP" }}
  selector:
{{- include "common.selectorLabels" . | nindent 4 }}
{{- include "webhook.selectorLabels" . | nindent 4 }}
  ports:
{{- .Values.webhook.service.ports | toYaml | nindent 4 }}

