{{/* 
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "manager.fullname" . }}-webhook-service
  namespace: greenhouse
  labels:
    app.kubernetes.io/created-by: {{ include "manager.fullname" . }}
    app.kubernetes.io/part-of: {{ include "manager.fullname" . }}
{{- include "webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type | default "ClusterIP" }}
  selector:
{{- include "common.selectorLabels" . | nindent 4 }}
{{- include "webhook.selectorLabels" . | nindent 4 }}
  ports:
{{- .Values.webhookService.ports | toYaml | nindent 4 }}

