---
name: Epic
about: Create an epic
title: "(context): "
assignees: ""
---

### Description

What problem does it solve? Why is it important?

### Objectives

List the high-level objectives or goals of this epic.

- Objective 1
- Objective 2
- Objective 3

### Acceptance Criteria

Define the criteria that must be met for this epic to be considered complete

- [ ] Criterion 1
- [ ] Criterion 2
- [ ] Criterion 3


### Dependencies

Identify any other epics, issues, or tasks that this epic depends on.

- Dependency 1
- Dependency 2
- Dependency 3

### Additional Notes

Any additional information, context, or considerations.
