{{/* 
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

{{- $fullName := include "website.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ required ".Values.ingress.className missing" .Values.ingress.className }}
  tls:
    - hosts:
        - "documentation.{{ required ".Values.global.dnsDomain missing" .Values.global.dnsDomain }}"
      secretName: tls-greenhouse-documentation
  rules:
    - host: "documentation.{{ required ".Values.global.dnsDomain missing" .Values.global.dnsDomain }}"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ required ".Values.service.port missing" .Values.service.port }}
