# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{ range $connector := .Values.connectors }}
---
apiVersion: dex.coreos.com/v1
kind: Connector
metadata:
  name: {{ $connector.id }}
config: {{ tpl $connector.config $ | fromYaml | toJson | b64enc }}
id: {{ $connector.id }}
name: {{ $connector.name }}
type: {{ $connector.type }}
{{ end }}
