{{/* 
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

{{ range $client := .Values.clients }}
---
apiVersion: dex.coreos.com/v1
kind: OAuth2Client
metadata:
  name: {{ printf "%s[REPLACE]" $client.id| replace "[REPLACE]" "\xcb\xf2\x9c\xe4\x84\x22\x23\x25" | b32enc |lower  | trimAll "=" }}
id: {{ $client.id }}
name: {{ $client.name | quote }}
secret: {{ $client.secret | quote }}
public: {{ default "false" $client.public }}
redirectURIs:
{{ toYaml $client.redirectURIs }}
{{ end }}
