{{/* 
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "idproxy.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "idproxy.selectorLabels" . | nindent 6 }}
