{{/* 
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "idproxy.fullname" . }}
rules:
- apiGroups:
  - "dex.coreos.com"
  resources:
  - "*"
  verbs:
  - watch
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: team-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: greenhouse
    app.kubernetes.io/part-of: greenhouse
  name: team-viewer-role
rules:
- apiGroups:
  - greenhouse.sap
  resources:
  - teams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - greenhouse.sap
  resources:
  - teams/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: organization-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: greenhouse
    app.kubernetes.io/part-of: greenhouse
    app.kubernetes.io/managed-by: kustomize
  name: organization-viewer-role
rules:
- apiGroups:
  - greenhouse.sap
  resources:
  - organizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - greenhouse.sap
  resources:
  - organizations/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "idproxy.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "idproxy.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "idproxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "idproxy.fullname" . }}-sa-te
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: team-viewer-role
subjects:
- kind: ServiceAccount
  name: {{ include "idproxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "idproxy.fullname" . }}-sa-ov
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: organization-viewer-role
subjects:
- kind: ServiceAccount
  name: {{ include "idproxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

