{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "idproxy.fullname" . }}
  labels:
    plugin: kube-monitoring
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      port: metrics
      scheme: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "idproxy.selectorLabels" . | nindent 6 }}
{{- end -}}
