# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "idproxy.fullname" . }}
  labels:
    {{- include "idproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: oidc
      protocol: TCP
      name: oidc
  selector:
    {{- include "idproxy.selectorLabels" . | nindent 4 }}
