# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: logshipping
description: A Helm chart for deploying fluent-bit with custom config

type: application
version: 0.0.2

dependencies:
  - name: fluent-bit
    repository: https://fluent.github.io/helm-charts
    version: 0.42.0
