# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

- op: add
  path: /spec/template/spec/serviceAccountName
  value: notification-controller
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: GOMAXPROCS
    valueFrom:
      resourceFieldRef:
        containerName: manager
        resource: limits.cpu
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: GOMEMLIMIT
    valueFrom:
      resourceFieldRef:
        containerName: manager
        resource: limits.memory