# SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            "anonymous-auth": "true"
            "service-account-issuer": "https://greenhouse-admin-control-plane:6443"
            "service-account-jwks-uri": "https://greenhouse-admin-control-plane:6443/openid/v1/jwks"