apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      targetPort: postgres
      port: {{ required ".Values.postgres.service.port missing" .Values.postgres.service.port }}
