apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "headscale.fullname" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ required ".Values.server.pvc.storage missing" .Values.server.pvc.storage }}
