{{/* 
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "headscale.fullname" . }}-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - patch
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "headscale.fullname" . }}-rbac
  labels:
  {{- include "headscale.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "headscale.fullname" . }}-role'
subjects:
- kind: ServiceAccount
  name: {{ include "headscale.fullname" . }}
  namespace: {{ .Release.Namespace }}
