apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headscale.fullname" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: {{ required ".Values.postgres.password missing" .Values.postgres.password | b64enc }}
  {{ if .Values.oidc.enabled }}
  oidc_client_secret: {{ required ".Values.oidc.clientSecret missing" .Values.oidc.clientSecret | b64enc }}
  {{ end }}
