# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0
global:
  dnsDomain: example.com
  dex:
    backend: postgres
    postgresql:
      postgresqlDatabase: dex
      postgresqlPort: 5432
      postgresqlUsername: dex


ingress:
  enabled: true

corsAllowedOrigins:
  - "*"
  - "foo"

clients:
- id: "greenhouse-ui"
  name: "Greenhouse UI"
  public: true
  redirectURIs:
    - https://dashboard.example.com
