# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

host: auth.example.com
ingress:
  enabled: false

connectors:
- id: admin
  name: Greenhouse Admin
  type: greenhouse-oidc
  config: |
    issuer: https://example.com
    clientID: nase
    clientSecret: hase
    redirectURI: https://{{ required "host missing" .Values.host }}/callback
    insecureEnableGroups: true
    userNameKey: login_name

clients:
- id: "greenhouse-ui"
  name: "Greenhouse UI"
  public: true
  redirectURIs:
    - https://dashboard.example.com
