# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: greenhouse.sap/v1alpha1
kind: Team
metadata:
  labels:
    app.kubernetes.io/name: greenhouse
    app.kubernetes.io/managed-by: kustomize
  name: team-sample
spec:
  # TODO(user): Add fields here
