# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: {{ include "manager.fullname" . }}-client-cert
spec:
  issuerRef:
    name: {{ include "manager.fullname" . }}-selfsigned
    kind: Issuer
  secretName: {{ include "manager.fullname" . }}-webhook-cert
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - {{ include "manager.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "manager.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
