# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

config:
  - cluster:
      name: greenhouse-admin
      namespace: greenhouse
      version: v1.31.0
      configPath: dev-env/localenv/greenhouse-admin-cluster.yaml
      postSetup:
        - command: kubectl --kubeconfig "${kubeconfig}" get cm kube-root-ca.crt -n default -o json | jq -r '.data."ca.crt"' | tee bin/greenhouse-admin-ca.crt
          vars:
            kubeconfig: kubeconfig
        - command: kubectl create clusterrolebinding ${clusterRoleBinding} --clusterrole=${clusterRole} --group=${group} --dry-run=client -o yaml | kubectl apply --kubeconfig "${kubeconfig}" -f -
          vars:
            kubeconfig: kubeconfig
            clusterRoleBinding: oidc-reviewer-binding
            clusterRole: system:service-account-issuer-discovery
            group: system:unauthenticated
    dependencies:
      - manifest:
          release: greenhouse
          chartPath: charts/idproxy
          crdOnly: true
      - manifest:
          release: greenhouse
          chartPath: charts/manager
          valuesPath: dev-env/localenv/dev.values.yaml
          crdOnly: false
          webhook:
            devMode: false
            dockerFile: "./"
            envs:
              - name: WEBHOOK_ONLY
                value: 'true'
  - cluster:
      name: greenhouse-remote
      configPath: dev-env/localenv/greenhouse-remote-cluster.yaml
