# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

config:
  - cluster:
      name: greenhouse-remote
  - cluster:
      name: greenhouse-admin
      namespace: greenhouse
    dependencies:
      - manifest:
          release: greenhouse
          chartPath: charts/idproxy
          crdOnly: true
      - manifest:
          release: greenhouse
          chartPath: charts/manager
          valuesPath: dev-env/localenv/dev.values.yaml
          crdOnly: false
          webhook:
            devMode: false
            dockerFile: "./"
            envs:
              - name: WEBHOOK_ONLY
                value: 'true'
