global:
  dnsDomain: localhost
  oidc:
    dashboardClientID: ""
alerts:
  enabled: false

replicas: 1

image:
  repository: ghcr.io/cloudoperators/juno-app-greenhouse
  digest: latest
  pullPolicy: IfNotPresent

dashboard:
  assetServerURL: origin
  environment: development
  demoUser:
    token: demo