# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Namespace
metadata:
  name: demo
---

apiVersion: v1
kind: Secret
metadata: 
  name: demo-oidc
  namespace: demo
type: greenhouse.sap/orgsecret
data:
  clientID: Zm9vYmFy
  clientSecret: VG9wU2VjcmV0ISEh
---

apiVersion: greenhouse.sap/v1alpha1
kind: Organization
metadata:
  name: demo
spec:
  description: Greenhouse Demo Organization
  mappedOrgAdminIdPGroup: DEMO_ORG_ADMIN
  authentication:
    oidc:
      clientIDReference:
        key: clientID
        name: demo-oidc
      clientSecretReference:
        key: clientSecret
        name: demo-oidc
      issuer: https://global.accounts.dev
      redirectURI: https://bogus.accounts.foo
