# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: greenhouse.sap/v1alpha1
kind: Organization
metadata:
  name: greenhouse
spec:
  description: Greenhouse Organization
  mappedOrgAdminIdPGroup: GREENHOUSE_ORG_ADMIN
