# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authz.fullname" . }}
  labels:
    {{- include "authz.labels" . | nindent 4 }}
  {{- with include "authz.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "authz.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authz.labels" . | nindent 8 }}
      {{- with include "authz.annotations" . }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "authz.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.ha.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "authz.selectorLabels" . | nindent 20 }}
                topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "authz.selectorLabels" . | nindent 14 }}
      {{- end }}
      {{- if or (and .Values.tls.enabled .Values.tls.useSecret) .Values.volumes }}
      volumes:
        {{- if and .Values.tls.enabled .Values.tls.useSecret }}
        - name: serving-certs
          secret:
            secretName: {{ include "authz.servingCertsSecretName" . }}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "authz.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /authz
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: webhook
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or (and .Values.tls.enabled .Values.tls.useSecret) .Values.volumeMounts }}
          volumeMounts:
            {{- if and .Values.tls.enabled .Values.tls.useSecret }}
            - name: serving-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
