{{/*
SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "authz.fullname" . }}
  labels:
    {{- include "authz.labels" . | nindent 4 }}
  {{- with include "authz.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["greenhouse.sap"]
    resources: ["*"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "authz.fullname" . }}
  labels:
    {{- include "authz.labels" . | nindent 4 }}
  {{- with include "authz.annotations" . }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "authz.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "authz.fullname" . }}