# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

## Certificate for APIServer
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: client-cert
  namespace: greenhouse
spec:
  issuerRef:
    name: greenhouse-ca-root
    kind: ClusterIssuer
  secretName: greenhouse-webhook-server-cert
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - greenhouse-webhook-service.greenhouse.svc
    - greenhouse-webhook-service.greenhouse.svc.cluster.local
    - host.docker.internal
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048