# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: greenhouse-
resources:
  - bootstrap.yaml
  - issuer.yaml
  - root.yaml
  - client.yaml