// SPDX-FileCopyrightText: 2026 SAP SE or an SAP affiliate company and Greenhouse contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFinalizerNamer creates a new instance of MockFinalizerNamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFinalizerNamer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFinalizerNamer {
	mock := &MockFinalizerNamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFinalizerNamer is an autogenerated mock type for the FinalizerNamer type
type MockFinalizerNamer struct {
	mock.Mock
}

type MockFinalizerNamer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFinalizerNamer) EXPECT() *MockFinalizerNamer_Expecter {
	return &MockFinalizerNamer_Expecter{mock: &_m.Mock}
}

// GetFinalizerName provides a mock function for the type MockFinalizerNamer
func (_mock *MockFinalizerNamer) GetFinalizerName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFinalizerName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFinalizerNamer_GetFinalizerName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFinalizerName'
type MockFinalizerNamer_GetFinalizerName_Call struct {
	*mock.Call
}

// GetFinalizerName is a helper method to define mock.On call
func (_e *MockFinalizerNamer_Expecter) GetFinalizerName() *MockFinalizerNamer_GetFinalizerName_Call {
	return &MockFinalizerNamer_GetFinalizerName_Call{Call: _e.mock.On("GetFinalizerName")}
}

func (_c *MockFinalizerNamer_GetFinalizerName_Call) Run(run func()) *MockFinalizerNamer_GetFinalizerName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFinalizerNamer_GetFinalizerName_Call) Return(s string) *MockFinalizerNamer_GetFinalizerName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFinalizerNamer_GetFinalizerName_Call) RunAndReturn(run func() string) *MockFinalizerNamer_GetFinalizerName_Call {
	_c.Call.Return(run)
	return _c
}
