apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.organization }}
  name: {{ .Chart.Name }}
data:
  scim-base-url: {{ required "env.SCIM_BASE_URL needs to be set" .Values.env.SCIM_BASE_URL }}