{{/* 
SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ .Values.organization }}
  name: {{ .Chart.Name }}
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 1000
      template:
        metadata:
          labels:
            name: {{ .Chart.Name }}
          annotations:
            checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
            checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        spec:
          serviceAccountName: {{ .Chart.Name }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: Always
            env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SCIM_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: scim-basic-auth-user
                  optional: false
            - name: SCIM_BASIC_AUTH_PW
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: scim-basic-auth-pw
                  optional: false
            - name: SCIM_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: scim-base-url
                  optional: false
            command:
            - /team-membership
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
          restartPolicy: "Never"
      