# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.organization }}
  name: {{ .Chart.Name }}
type: Opaque
data:
  scim-basic-auth-user: {{ required "env.SCIM_BASIC_AUTH_USER needs to be set" .Values.env.SCIM_BASIC_AUTH_USER | b64enc }}
  scim-basic-auth-pw: {{ required "env.SCIM_BASIC_AUTH_PW needs to be set" .Values.env.SCIM_BASIC_AUTH_PW | b64enc }}