# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-secrets
  labels:
    app: fluent-bit-fluent-bit
    release: fluent-bit
data:
  OPENSEARCH_GREENHOUSE_PWD: {{ index .Values "fluent-bit" "backend" "opensearch" "http_passwd" |  b64enc }}
