apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-secrets
  labels:
    app: fluent-bit-fluent-bit
    release: fluent-bit
data:
  OPENSEARCH_GREENHOUSE_PWD: {{ index .Values "fluent-bit" "backend" "opensearch" "http_passwd" |  b64enc }}
