# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: teamrolebindings.greenhouse.sap
  annotations:
    cert-manager.io/inject-ca-from: greenhouse/greenhouse-client-cert