# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: teamrolebindings.greenhouse.sap
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: greenhouse
          name: greenhouse-webhook-service
          path: /convert
      conversionReviewVersions:
      - v1alpha2
      - v1alpha1
      - v1beta1 # v1beta1 or v1 is required by Kubernetes to bundle the conversion webhook