# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

dex-sql-backend:
  variations:
    true: true
    false: false
  defaultRule:
    variation: false

dex-kubernetes-backend:
  variations:
    true: true
    false: false
  defaultRule:
    variation: true