# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: headscale
description: Headscale
type: application
version: 0.1.2
appVersion: 0.22.3
