apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ui-index-html-cm

data:
  index.html: |
    <!DOCTYPE html>
    <html style="margin: 0; padding: 0; display: flex; flex-direction: column;">
      <head>
        <title>Greenhouse</title>
        <link rel="icon" sizes="any" href="{{ required ".Values.juno.assetServerURL missing" .Values.juno.assetServerURL }}/assets/favicon.ico"/>
        <link rel="icon" type="image/png" sizes="16x16"href="{{ required ".Values.juno.assetServerURL missing" .Values.juno.assetServerURL }}/assets/favicon-16x16.png"/>
        <link rel="icon" type="image/png" sizes="32x32"href="{{ required ".Values.juno.assetServerURL missing" .Values.juno.assetServerURL }}/assets/favicon-32x32.png"/>
      </head>
      <body style="height: 100vh; flex-grow: 1; margin: 0; padding: 0;">
        <script
          src="{{ required ".Values.juno.assetServerURL missing" .Values.juno.assetServerURL }}/apps/widget-loader@latest/build/app.js" 
          data-name="greenhouse"
          data-version="{{ default "latest" .Values.juno.greenhouse.version }}"
          data-props-auth-issuer-url={{ required ".Values.oidcIssuerUrl" .Values.oidcIssuerUrl| quote }}
          data-props-auth-client-id={{ required ".Values.oidcClientId" .Values.oidcClientId | quote }}
          data-props-api-endpoint={{ required ".Values.k8sApiEndpoint" .Values.k8sApiEndpoint | quote }}
          data-props-demo-user-token={{ required ".Values.demoUser.token" .Values.demoUser.token | quote }}
          data-props-environment={{ required ".Values.environment" .Values.environment | quote }}>
        </script>
      </body>
    </html>
