# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

kind: Service
apiVersion: v1

metadata:
  name: {{ .Release.Name }}-ui

spec:
  selector:
    app: dashboard
  ports:
    - name: dashboard
      port: 80
      protocol: TCP
      targetPort: dashboard
