# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./bin/authz-certs
        containerPath: /etc/kubernetes/webhook/certs
      - hostPath: ./dev-env/webhook
        containerPath: /etc/kubernetes/webhook
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            "anonymous-auth": "true"
            "service-account-issuer": "https://greenhouse-admin-control-plane:6443"
            "service-account-jwks-uri": "https://greenhouse-admin-control-plane:6443/openid/v1/jwks"
            "authorization-config": "/etc/kubernetes/webhook/structured-authz-insecure.yaml"
          extraVolumes:
            - name: authz-webhook
              hostPath: /etc/kubernetes/webhook
              mountPath: /etc/kubernetes/webhook
              readOnly: true