{
 "title": "Greenhouse Proxy Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(http_requests_total, namespace)"
    }
   },
   {
    "name": "proxy",
    "query": {
     "query": "label_values(http_requests_total{namespace=~\"$namespace\"},  service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "${proxy}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "proxy" },
  {
   "title": "HTTP Requests Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (method, code) (rate(http_requests_total{service=~\"$proxy\"}[5m]))",
     "legendFormat": "{{method}}/{{code}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (service, le) (http_request_duration_seconds_bucket{service=~\"$proxy\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP Response Size Bytes",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (service, le) (http_response_size_bytes_bucket{service=~\"$proxy\"})",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}