//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha3

import (
	"github.com/cloudoperators/greenhouse/api/meta/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOptionOverride) DeepCopyInto(out *ClusterOptionOverride) {
	*out = *in
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make([]v1alpha1.PluginOptionValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOptionOverride.
func (in *ClusterOptionOverride) DeepCopy() *ClusterOptionOverride {
	if in == nil {
		return nil
	}
	out := new(ClusterOptionOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedPluginStatus) DeepCopyInto(out *ManagedPluginStatus) {
	*out = *in
	in.ReadyCondition.DeepCopyInto(&out.ReadyCondition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedPluginStatus.
func (in *ManagedPluginStatus) DeepCopy() *ManagedPluginStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedPluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginPreset) DeepCopyInto(out *PluginPreset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginPreset.
func (in *PluginPreset) DeepCopy() *PluginPreset {
	if in == nil {
		return nil
	}
	out := new(PluginPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PluginPreset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginPresetList) DeepCopyInto(out *PluginPresetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PluginPreset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginPresetList.
func (in *PluginPresetList) DeepCopy() *PluginPresetList {
	if in == nil {
		return nil
	}
	out := new(PluginPresetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PluginPresetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginPresetSpec) DeepCopyInto(out *PluginPresetSpec) {
	*out = *in
	in.Plugin.DeepCopyInto(&out.Plugin)
	in.ClusterSelector.DeepCopyInto(&out.ClusterSelector)
	if in.ClusterOptionOverrides != nil {
		in, out := &in.ClusterOptionOverrides, &out.ClusterOptionOverrides
		*out = make([]ClusterOptionOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginPresetSpec.
func (in *PluginPresetSpec) DeepCopy() *PluginPresetSpec {
	if in == nil {
		return nil
	}
	out := new(PluginPresetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginPresetStatus) DeepCopyInto(out *PluginPresetStatus) {
	*out = *in
	in.StatusConditions.DeepCopyInto(&out.StatusConditions)
	if in.PluginStatuses != nil {
		in, out := &in.PluginStatuses, &out.PluginStatuses
		*out = make([]ManagedPluginStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginPresetStatus.
func (in *PluginPresetStatus) DeepCopy() *PluginPresetStatus {
	if in == nil {
		return nil
	}
	out := new(PluginPresetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginTemplateSpec) DeepCopyInto(out *PluginTemplateSpec) {
	*out = *in
	out.PluginDefinitionRef = in.PluginDefinitionRef
	if in.OptionValues != nil {
		in, out := &in.OptionValues, &out.OptionValues
		*out = make([]v1alpha1.PluginOptionValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginTemplateSpec.
func (in *PluginTemplateSpec) DeepCopy() *PluginTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PluginTemplateSpec)
	in.DeepCopyInto(out)
	return out
}
