apiVersion: greenhouse.sap/v1alpha1
kind: Catalog
metadata:
  name: greenhouse-extensions-latest
  namespace: {{ .Chart.Name }}
spec:
  sources:
    - ref:
        branch: main
      repository: https://github.com/cloudoperators/greenhouse-extensions
      resources:
        - doop/plugindefinition.yaml
        - heureka/plugindefinition.yaml
        - supernova/plugindefinition.yaml
