apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "manager.fullname" . }}-manager-config
  labels:
  {{- include "manager.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: |
    {{- .Files.Get "etc/controller_manager_config.yaml" | nindent 4 }}
