//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/cloudoperators/greenhouse/api/meta/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOptionOverride) DeepCopyInto(out *ClusterOptionOverride) {
	*out = *in
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make([]v1alpha1.PluginOptionValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOptionOverride.
func (in *ClusterOptionOverride) DeepCopy() *ClusterOptionOverride {
	if in == nil {
		return nil
	}
	out := new(ClusterOptionOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSelector) DeepCopyInto(out *ClusterSelector) {
	*out = *in
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSelector.
func (in *ClusterSelector) DeepCopy() *ClusterSelector {
	if in == nil {
		return nil
	}
	out := new(ClusterSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedPluginStatus) DeepCopyInto(out *ManagedPluginStatus) {
	*out = *in
	in.ReadyCondition.DeepCopyInto(&out.ReadyCondition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedPluginStatus.
func (in *ManagedPluginStatus) DeepCopy() *ManagedPluginStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedPluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginPreset) DeepCopyInto(out *PluginPreset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginPreset.
func (in *PluginPreset) DeepCopy() *PluginPreset {
	if in == nil {
		return nil
	}
	out := new(PluginPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PluginPreset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginPresetList) DeepCopyInto(out *PluginPresetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PluginPreset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginPresetList.
func (in *PluginPresetList) DeepCopy() *PluginPresetList {
	if in == nil {
		return nil
	}
	out := new(PluginPresetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PluginPresetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginPresetSpec) DeepCopyInto(out *PluginPresetSpec) {
	*out = *in
	in.Plugin.DeepCopyInto(&out.Plugin)
	in.ClusterSelector.DeepCopyInto(&out.ClusterSelector)
	if in.ClusterOptionOverrides != nil {
		in, out := &in.ClusterOptionOverrides, &out.ClusterOptionOverrides
		*out = make([]ClusterOptionOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginPresetSpec.
func (in *PluginPresetSpec) DeepCopy() *PluginPresetSpec {
	if in == nil {
		return nil
	}
	out := new(PluginPresetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginPresetStatus) DeepCopyInto(out *PluginPresetStatus) {
	*out = *in
	in.StatusConditions.DeepCopyInto(&out.StatusConditions)
	if in.PluginStatuses != nil {
		in, out := &in.PluginStatuses, &out.PluginStatuses
		*out = make([]ManagedPluginStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginPresetStatus.
func (in *PluginPresetStatus) DeepCopy() *PluginPresetStatus {
	if in == nil {
		return nil
	}
	out := new(PluginPresetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginTemplateSpec) DeepCopyInto(out *PluginTemplateSpec) {
	*out = *in
	if in.OptionValues != nil {
		in, out := &in.OptionValues, &out.OptionValues
		*out = make([]v1alpha1.PluginOptionValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginTemplateSpec.
func (in *PluginTemplateSpec) DeepCopy() *PluginTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PluginTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropagationStatus) DeepCopyInto(out *PropagationStatus) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropagationStatus.
func (in *PropagationStatus) DeepCopy() *PropagationStatus {
	if in == nil {
		return nil
	}
	out := new(PropagationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamRoleBinding) DeepCopyInto(out *TeamRoleBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamRoleBinding.
func (in *TeamRoleBinding) DeepCopy() *TeamRoleBinding {
	if in == nil {
		return nil
	}
	out := new(TeamRoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamRoleBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamRoleBindingList) DeepCopyInto(out *TeamRoleBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TeamRoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamRoleBindingList.
func (in *TeamRoleBindingList) DeepCopy() *TeamRoleBindingList {
	if in == nil {
		return nil
	}
	out := new(TeamRoleBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamRoleBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamRoleBindingSpec) DeepCopyInto(out *TeamRoleBindingSpec) {
	*out = *in
	if in.Usernames != nil {
		in, out := &in.Usernames, &out.Usernames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ClusterSelector.DeepCopyInto(&out.ClusterSelector)
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamRoleBindingSpec.
func (in *TeamRoleBindingSpec) DeepCopy() *TeamRoleBindingSpec {
	if in == nil {
		return nil
	}
	out := new(TeamRoleBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamRoleBindingStatus) DeepCopyInto(out *TeamRoleBindingStatus) {
	*out = *in
	in.StatusConditions.DeepCopyInto(&out.StatusConditions)
	if in.PropagationStatus != nil {
		in, out := &in.PropagationStatus, &out.PropagationStatus
		*out = make([]PropagationStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamRoleBindingStatus.
func (in *TeamRoleBindingStatus) DeepCopy() *TeamRoleBindingStatus {
	if in == nil {
		return nil
	}
	out := new(TeamRoleBindingStatus)
	in.DeepCopyInto(out)
	return out
}
