name: Changelog

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  release:
    permissions:
        contents: write
    runs-on: default
    steps:
      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          outputFile: "./CHANGELOG.md"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                {
                    "title": "## 🚀 Features",
                    "labels": ["feat", "feature"]
                },
                {
                    "title": "## 🐛 Fixes",
                    "labels": ["fix", "bug"]
                },
                {
                    "title": "## Security"
                    "labels": ["chore(deps)"]
                },
                {
                    "title": "## Other",
                    "labels": []
                }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "target": "$1"
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}