name: Changelog

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  release:
    permissions:
        contents: write
    runs-on: default
    steps:
      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          outputFile: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}