# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0

name: REUSE Compliance Check

on: [pull_request]

jobs:
  reuse:
    uses: cloudoperators/common/.github/workflows/shared-reuse.yaml@f87e1e6b7889707a9c10d1a8a9f9f481eb311c06 # main
