name: CI Release Action

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: [ ubuntu-latest ]
    permissions:
        contents: write
        discussions: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: 'go.mod'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: release
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          distribution: goreleaser
          version: ${{ vars.GITHUB_SHA }}
          args: release --config .github/.goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@bcae7115752d4ed746ff92feb666574428a79415 # v6.2.1
        with:
          configuration: .github/changelog-config.json
          ignorePreReleases: true
          outputFile: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
            draft: true
            generate_release_notes: false
            body_path: CHANGELOG.md
            token: ${{ secrets.GITHUB_TOKEN }}
