name: CI Release Action

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: [ ubuntu-latest ]
    permissions:
        contents: write
        discussions: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: 'go.mod'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: release
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          distribution: goreleaser
          version: ${{ vars.GITHUB_SHA }}
          args: release --config .github/.goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@a34a8009a9588bb86b02a873cf592440e96a5da8 # v6.1.1
        with:
          configuration: .github/changelog-config.json
          ignorePreReleases: true
          outputFile: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@1853d73993c8ca1b2c9c1a7fede39682d0ab5c2a # v2.5.3
        with:
            draft: true
            generate_release_notes: false
            body_path: CHANGELOG.md
            token: ${{ secrets.GITHUB_TOKEN }}
