name: Packages Cleanup

on:
  workflow_dispatch: {}

jobs:
  cleanup:
    name: ghcr.io cleanup action
    runs-on: ubuntu-latest
    steps:
        - uses: dataaxiom/ghcr-cleanup-action@v1
          with:
            dry-run: true
            exclude-tags: main
            delete-untagged: true
            delete-ghost-images: true
            delete-partial-images: true
            keep-n-tagged: 3
            token: ${{ secrets.GITHUB_TOKEN }}