# Run it locally with act (https://github.com/nektos/act)
#  1. Install act:
#     `brew install act`
#  2. Create a .secret file with the following content:
#     `GITHUB_TOKEN=your_github_token`
# WORKFLOW CALL
# 1.Create a act_workflow_call.json file with the following content:
#     `{"inputs": {"runs-on": "ubuntu-latest", "api-dir": "./pkg/apis/greenhouse/v1alpha1", "config": "./hack/gen-crd-api-reference-docs/config.json", "template-dir": "./hack/gen-crd-api-reference-docs/templates", "out-file": "./website/content/docs/reference/api/crds.md"}}`
# 2. Run the following command:
#     `act workflow_call --container-architecture linux/amd64 --eventpath act_workflow_call.json -W .github/workflows/gen-crd-api-to-docs.yaml`

name: Generate CRD API Reference Documentation

on:
  workflow_call:
    inputs:
      runs-on:
        description: "The runner to use for the job"
        required: false
        default: "default"
        type: string
      api-dir:
        description: "The directory containing the API definitions"
        required: true
        type: string
      config:
        description: "The configuration file used to generate the documentation"
        required: true
        type: string
      template-dir:
        description: "The directory containing the templates used to generate the documentation"
        required: true
        type: string
      out-file:
        description: "The output file with the generated documentation"
        required: true
        type: string

jobs:
  generate-crd-api-reference-docs:
    runs-on: ${{ inputs.runs-on}}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Inputs
        run: |
          echo "====${{ github.workflow }} Inputs===="
          echo "Inputs: ${{ toJson(inputs) }}"
          echo "===="

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Verify Go version
        run: go version

      - name: gen-crd-api-reference-docs installation
        run: |
          go install github.com/ahmetb/gen-crd-api-reference-docs@latest

      - name: Generate CRD API Reference Docs
        run: |
          gen-crd-api-reference-docs -api-dir=${{ inputs.api-dir }} -config=${{ inputs.config }} -template-dir=${{ inputs.template-dir }} -out-file=${{ inputs.out-file }}

      - name: Output Changes
        run: |
          echo "====${{ github.workflow }} Outputs===="
          cat ${{ inputs.out-file }}
          echo "===="
          git status
          echo "===="
          ls -la
          echo "===="

      - name: Apply Changes
        uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: CRD API Docs Bot
          author_email: crd_api_docs_bot@github.com
          message: "Automatic genaration of CRD API Docs"
