name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: default
    permissions:
        contents: write
        discussions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: .github/changelog-config.json
          outputFile: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
            draft: true
            generate_release_notes: true
            body_path: CHANGELOG.md
            token: ${{ secrets.GITHUB_TOKEN }}