name: GitHub Actions Version Updater

on: workflow_dispatch
  #schedule:
  #  - cron:  '0 10 * * 1'

jobs:
  build:
    runs-on: [ default ]

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_title: 'Update GitHub Action Versions'
          update_version_with: 'release-tag'
          release_types: "major"
          pull_request_labels: "dependencies"
          pull_request_branch: "fix/actions-update"
