name: Issue Project Sync
on:
  issues:
    types: [labeled]

permissions:
  issues: read

jobs:
  sync:
    if: github.event.label.name == 'backlog'
    runs-on: ubuntu-latest
    steps:
      - uses: cloudoperators/common/workflows/issue-project-sync@d138f9922c75ed1e1ad3ae3bfb68dd8ae3284dc6 # main
        with:
          GH_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}