name: Issue Triage
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudoperators/common/workflows/issue-triage@d138f9922c75ed1e1ad3ae3bfb68dd8ae3284dc6 # main