name: Issue Project Sync
on:
  issues:
    types: [labeled]

permissions:
  issues: read

jobs:
  sync:
    if: github.event.label.name == 'backlog'
    runs-on: ubuntu-latest
    steps:
      - uses: cloudoperators/common/workflows/issue-project-sync@c5ee48b3e45f779545e42861b3f361cd3848abd8 # main
        with:
          GH_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}