name: Issue Triage
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudoperators/common/workflows/issue-triage@f87e1e6b7889707a9c10d1a8a9f9f481eb311c06 # main