name: Issue Project Sync
on:
  issues:
    types: [labeled]

permissions:
  issues: read

jobs:
  sync:
    if: github.event.label.name == 'backlog'
    runs-on: ubuntu-latest
    steps:
      - uses: cloudoperators/common/workflows/issue-project-sync@ab7fac711675c77ba025bfde04f08175a4476546 # main
        with:
          GH_TOKEN: ${{ secrets.GH_PROJECT_TOKEN }}