name: Issue Triage
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudoperators/common/workflows/issue-triage@f26f4ef8a904160c45e9fc942423d6be2ffd0f03 # main