name: Check & Fix License Header
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  license:
    name: Apply Licence Header
    permissions:
      contents: write  # Only used when `apply_header: true` else the permission is `read` see: https://github.com/cloudoperators/common/blob/8f15c13b6f4c1631c7e6f6dff5c3300452e9b5b6/.github/workflows/shared-license.yaml#L21-L22
    uses: cloudoperators/common/.github/workflows/shared-license.yaml@17d3d6b80851574fcd8c7b6e5c4fe6aee2922359
    secrets:
      app_id: ${{ secrets.CLOUDOPERATOR_APP_ID }}
      private_key: ${{ secrets.CLOUDOPERATOR_APP_PRIVATE_KEY }}
