name: Close inactive issues
on:
  schedule:
    - cron: "35 1 * * *"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    uses: cloudoperators/common/.github/workflows/shared-stale.yaml@f26f4ef8a904160c45e9fc942423d6be2ffd0f03 # main
