name: Close inactive issues
on:
  schedule:
    - cron: "35 1 * * *"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    uses: cloudoperators/common/.github/workflows/shared-stale.yaml@c5ee48b3e45f779545e42861b3f361cd3848abd8 # main
