name: Close inactive issues
on:
  schedule:
    - cron: "35 1 * * *"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    uses: cloudoperators/common/.github/workflows/shared-stale.yaml@c12810ffe8dfb7f4f907959e9e85632d5ed5469e # main
